name: build-puppeteer
run-name: Build puppeteer Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'scenarios/**'
      - 'gunet.js'
      - 'Dockerfile'
      - 'package.json'      

jobs:
  build-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Athens"
      - name: Get date
        id: date
        run: echo "push_date=$(date '+%H:%M@%d/%m/%Y')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Base image
        uses: docker/build-push-action@v3
        with:
          context: puppeteer
          file: ./Dockerfile
          push: true
          tags: ghcr.io/gunet/puppeteer:latest
          labels: gr.gunet.puppeteer.latest.pushdate=${{ steps.date.outputs.push_date }}
          cache-from: type=registry,ref=ghcr.io/gunet/puppeteer:buildcache
          cache-to: type=registry,ref=ghcr.io/gunet/puppeteer:buildcache,mode=max